[project]
name = "hackon"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    "torch>=2.6.0",
    "torchvision>=0.21.0",
    "opencv-python-headless>=4.9.0",
    "tqdm",
    "numpy>=1.26.0,<3.0.0",
    "pillow>=10.0.0",
    "matplotlib>=3.8.0",
    "streamlit>=1.28.0",
    "scipy>=1.14.0",
    "transformers>=4.40.0",
    "accelerate>=1.0.0",
    "albumentations>=1.4.0",
    "segmentation-models-pytorch>=0.3.4",
]
